### ISSUE TITLE
Refresh token- No authorization configuration available for refresh request 

### ISSUE THREAD

**Issue by nsspl-india** [okta/samples-android#28]
Hi Team,

I did try the custom-sign-in app.I did authentication, logged in etc work well. but When I pressed the refresh token buttton then I got an error "No authorization configuration available for refresh request ". I followed the right instructions and I don't see any problem in my okta_auth_app_config.json file.
Could you please help me out of this problem ?

**Comment by dragosgaftoneanu-okta** [comment]
Hi @ihormartsekha-okta , @FeiChen-okta 

Can you please review the error above? I have managed to reproduce this error as well on my end.

**Comment by FeiChen-okta** [comment]
The issue is with the OktaAppAuth library. I've put in a fix https://github.com/okta/okta-sdk-appauth-android/pull/98 once that is merged I'll release a new version 0.2.4.

**Comment by nsspl-india** [comment]
Hi @FeiChen-okta,

I tried the latest OktaAppAuth library and It is also not working. I got the errors when I opened and build the okta/okta-sdk-appauth-android project into the Android Studio.The errors seems that net.openid package has missed in the OktaAppAuth library. Could you please review the problem ? I need the solution of the problem.

**Comment by FeiChen-okta** [comment]
@nsspl-india 

I have made a release 0.2.4
you can update your gradle file with this version
```gradle
    implementation 'com.okta.android:appauth-android:0.2.4'
```

**Comment by nsspl-india** [comment]
> @nsspl-india
> 
> I have made a release 0.2.4
> you can update your gradle file with this version
> 
> ```groovy-gradle
>     implementation 'com.okta.android:appauth-android:0.2.4'
> ```

It works.Thank you :)
