### ISSUE TITLE
Custom-Sign-In App has crashed in Android 6.0 and 5.0 O/S

### ISSUE THREAD

**Issue by nsspl-india** [okta/samples-android#31]
Hi Team,

I found an issue that I can't run the custom-sign-in app in android  6.0 (Marshmallow O/S) and 5.0 device (lollipop O/S) and It usually goes crash when the app is started.

So could you please look at this issue ? I will be help if you can provide the solution as soon as possible.I need this urgent.

Thanks !

**Comment by FeiChen-okta** [comment]
Custom sign in only works on Android 7 and above. This is due to the usage of Java 8 in the authentication SDK.

**Comment by nsspl-india** [comment]
In the custom-sign-in app, you mentioned minsdk 21, it means that app will work android 5.0 and above. Can you check minsdk version?

**Comment by FeiChen-okta** [comment]
The build.gradle is set to min 21. But that is wrong. We are working on a library that is compatible with lower android versions. In the mean time you can directly use the REST API endpoint  in: https://developer.okta.com/docs/api/resources/authn/#authentication-operations
to get a sessionToken.

**Comment by nsspl-india** [comment]
@FeiChen-okta When could I get compatible with lower android version 21 ? I really need a stable for low android version 21.

**Comment by FeiChen-okta** [comment]
@nsspl-india You can try using the bazel approach we have added in a separate branch:
https://github.com/okta/okta-oidc-android/tree/authn_android
Check the readme for more information.

**Comment by JayNewstrom** [comment]
We've updated the documentation and samples to show how to support Android 21+.
