### ISSUE TITLE
Insight into how to accomplish Native Sign-In

### ISSUE THREAD

**Issue by yashrao99** [okta/samples-android#33]
I have a more generic question about the code-base. 

I am trying to accomplish native sign-in without using the okta widget. I have successfully used the Okta-Auth SDK to take the email/password combo and return a session Token. 

Where I am lost, is how to login using this session token. I see the method `authenticate` using the `OktaAppAuth` object, yet the authenticate listener returns nothing and I get an error when I try to use this method with the session token. 

However, the rest of the code uses a package called `com.okta.oidc` to configure a lot of parameters to sign-in using the android SDK, which I do not have in any of my packages. Did something change with the SDKs? 

Are there some changes that I am not aware of in order to get this work?

Any help would be appreciated

**Comment by FeiChen-okta** [comment]
Hi @yashrao99 We have moved to another SDK and are in the process of updating these samples.

https://github.com/okta/okta-oidc-android
