### ISSUE TITLE
app crashes while downloaded from playstore but working while building from android studio

### ISSUE THREAD

**Issue by swagatdishri** [okta/samples-android#45]
Caused by c.b.c.b.c
Unable to load class named [com.okta.authn.sdk.impl.client.DefaultAuthenticationClientBuilder] from the thread context, current, or system/application ClassLoaders. All heuristics have been exhausted. Class could not be found.

**Comment by JayNewstrom** [comment]
This looks like a proguard/R8 configuration issue. Can you use one of our samples to reproduce the issue so we can fix this? Thanks!
