### ISSUE TITLE
Okta - Received an error message in Custom-sign-in sample

### ISSUE THREAD

**Issue by ggueta** [okta/samples-android#46]
Hi,

I downloaded the Android Sample App 
I used in ‘custom-sign-in’ sample, defined all setting of MFA in developer account and in android code (java),
The application worked fine until confirm the push notification or after enter code (manual) and press on “Verify” button,
I get the following error: “Response state param did not match request state” (code 9)

**Why do I get the above error?**

**Comment by ggueta** [comment]
![The error message](https://user-images.githubusercontent.com/65312285/81867654-b9435300-9579-11ea-8aac-9c7349c93dbe.PNG)

**Comment by FeiChen-okta** [comment]
Hi @ggueta the sample does not handle all the MFA flow. The state param error is probably due to the account you are using does not have MFA enabled, MFA enrolled. or in the process of enrolling but is awaiting activation.

custom-sign-in sample does not do all these state and errors like chrome custom tab does. We don't have an equivalent of the login page from chrome which handles these for native apps. You'll have to implement your custom state handler like:
https://github.com/okta/okta-auth-java#usage-guide

**Comment by ggueta** [comment]
Hi,

My organization is a customer of Okta, now we are searching to add a new security service of Okta for the application (Android - Java) of the organization.
Before we are purchase the service, we need to check the developer environment of it, so I opened developer account in  Okta, see the following Details:
![image](https://user-images.githubusercontent.com/65312285/82131388-679b0280-97dd-11ea-9096-9f9cf371409d.png)

Note, I defined in my developer account all the settings for MFA, if I try to connect to my developer account I receive push notification in “Okta Verify” and after approve the notification  I success to enter my account,  which means the MFA works great.
But if I try to enter from the application (sample – custom-sign-in) I received the error after approve the push notification in “Okta Verify”,  the application received the approve from “Okta Verify” but I think the authentication is failed and I don’t know why,
I need your help with this issue,
Attached screenshot

Please advice
![MFA](https://user-images.githubusercontent.com/65312285/82131392-78e40f00-97dd-11ea-8454-edcad55d2a3b.JPG)

**Comment by FeiChen-okta** [comment]
Hi @ggueta Your sign-on policy looks correct. Can you check your multi factor policy? for reference it can be found here https://developer.okta.com/docs/guides/mfa/-/set-up-org/
This is to enable using Okta Verify or Google Authenticator.

The sample does not do enrollment of the MFA. This is the step where you use Okta verify to scan a QR code or click a email activation link. For setting up MFA you can try using the chrome sample https://github.com/okta/samples-android/tree/master/sign-in-kotlin

**Comment by ggueta** [comment]
Hi,
Attached screenshots of multi factor policy

![image](https://user-images.githubusercontent.com/65312285/82261093-19b20600-9967-11ea-9f01-f161e165c190.png)

![image](https://user-images.githubusercontent.com/65312285/82261146-2c2c3f80-9967-11ea-859b-74fca0f09369.png)

Is it set correctly?

**Comment by FeiChen-okta** [comment]
Yes that looks correct. You can try the kotlin example and sign in with chrome. you should get a prompt to register for MFA with okta verify.

**Comment by razvan-negri** [comment]
@FeiChen-okta Thanks for the update. It works fine with a global MFA policy but not with an app context MFA policy.

There was a similar thread a while back but the part about handling the stateToken is still unanswered https://devforum.okta.com/t/support-for-application-level-mfa-sign-on-policies/190/2

The step-up feature was enabled but didn't help.
We couldn't find any documentation on this subject, how do we handle the per app MFA authorization?

**Comment by FeiChen-okta** [comment]
Hi @razvan-negri If using custom login. The state token is passed to the client on initial login, you can use the stateHandler or the returned response.
```kotlin
val response:AuthenticationResponse = authenticationClient.authenticate(
    username, password.toCharArray(),null, null)
```
The stateToken you can get from the response.
For more information on how to use the authn endpoints:
https://developer.okta.com/docs/reference/api/authn/#request-parameters-for-enroll-factor

Are you using chrome custom tabs to test the MFA policy? I would suggest using the chrome login first to see if your policy is setup correctly. Then you can implement the custom sign-in.

**Comment by JayNewstrom** [comment]
It looks like Fei was able to answer your questions, if you have any others please feel free to comment, reopen, or create a new issue. Thanks!
