### ISSUE TITLE
Discovery URI Guidance 

### ISSUE THREAD

**Issue by jamesreeder-okta** [okta/samples-android#56]
On the Kotlin sign-in example page, the setup configuration file instructions state to use your Okta Domain for the **discovery_uri** parameter. This is confusing for people not familiar with how AS's work within Okta.

It would be better if we could expand the instructions or at least improve referencing to the following section in the **okta-oidc-android** README page.

---

> **Note**: .well-known/openid-configuration will be appended to your discoveryUri if it is missing.
> 
> discoveryUri is: https://{yourOktaDomain}/oauth2/${authServerId} then .well-known/openid-configuration is added.
> discoveryUri is: https://{yourOktaDomain} then .well-known/openid-configuration is added.
> discoveryUri is: https://{yourOktaDomain}/oauth2/default then .well-known/openid-configuration is added.
> discoveryUri is: https://{yourOktaDomain}/oauth2/${authServerId}/.well-known/openid-configuration nothing is added.
> discoveryUri is: https://{yourOktaDomain}/oauth2/${authServerId}/.well-known/oauth-authorization-server nothing is added.
> 
>

**Comment by JayNewstrom** [comment]
I found this confusing the first time I set it up as well. We have this issue for other samples as well. 

I propose we create a configuration section in the okta-oidc-android repo and link all other samples to it. The samples that would link to it would include the ones in this repo, as well as the react native samples.

Thoughts @FeiChen-okta?

**Comment by FeiChen-okta** [comment]
Yes setting up a link to a configuration section in the main repository or the dev docs is a good idea.

**Comment by JayNewstrom** [comment]
Internal Ref: OKTA-342762

**Comment by JayNewstrom** [comment]
I've submitted a few PRs:

- https://github.com/okta/samples-android/pull/57
- https://github.com/okta/okta-oidc-android/pull/200

This should help with discovery_uri understand for new okta users.
I'm going to close this issue as resolved. Feel free to reopen or open a new issue if you have any other suggestiong.
Thanks!
