### ISSUE TITLE
Redirection not working in android release build

### ISSUE THREAD

**Issue by roym5252** [okta/samples-android#61]
Okta redirection is not working in android release build with minifyenabled set to true

```
defaultConfig {
        applicationId "com.companyname.appname"
        manifestPlaceholders = [
                appAuthRedirectScheme: 'com.okta.companyname-prod'
        ]
    }
```

It is properly getting redirected in release build if I set minifyenabled false. If it is set to true then the progress bar is displayed infinitely.

**Comment by NikitaAvraimov-okta** [comment]
Created internal story to research this issue, ref OKTA-379061. In the meantime you can try editing your proguard config to keep library untouched:
`-keep class com.okta.** { *; }`

**Comment by NikitaAvraimov-okta** [comment]
It is expected from developers to add okta to proguard exceptions.
Please feel free to reach out if you have other questions.
