### ISSUE TITLE
Sample App Download From Admin Page Not Pre-Populating Configs

### ISSUE THREAD

**Issue by mitchross** [okta/samples-android#68]
![image](https://user-images.githubusercontent.com/6330506/130134992-d3791c9f-4f89-44e3-85eb-2fa4492dbab7.png)
![image](https://user-images.githubusercontent.com/6330506/130135021-f9c6a09f-48d1-42f1-ac42-ab4057a02fb6.png)

Where on iOS it is
![image](https://user-images.githubusercontent.com/6330506/130135242-4a3d857c-82fc-4c46-9fd2-5837e3b11b78.png)

**Comment by JayNewstrom** [comment]
Hi, thanks for the report. I'll forward this on to the right team to fix.

**Comment by JayNewstrom** [comment]
Internal ref: OKTA-421614

**Comment by JayNewstrom** [comment]
The original issue should be fixed now.
